; ============================================================
;   PlatformIO-Konfiguration für alle M5Stick-Varianten
; ============================================================

[platformio]
default_envs = 
    m5stickc
    m5stickc_plus2

src_dir = .
include_dir = .

[common]
custom_flags =
    ; display the number of loop cycles per second
    ; --------------------------------------------
    ;-DmeasurePerformance

    ; Secure Elements
    ; ---------------
    ;-DuseSecEl

    ; Use AI
    ; ------
    ;-DuseAI 

custom_libs = 
    ; Secure Elements
    ; ---------------
    ;../libraries/IoTT_SecurityElements

    ; Use AI
    ; ------
    ;../libraries/EmergencyStop_inferencing
    ;../libraries/IoTT_VoiceControl

; ------------------------------------------------------------
;   Gemeinsame Einstellungen für alle Boards
; ------------------------------------------------------------
[env]
platform = 
    platform = espressif32 @ 6.12.0

framework = arduino

platform_packages =

monitor_speed = 115200
lib_deps =
    ../libraries/Adafruit_BNO055
    ../libraries/Adafruit_PWM_Servo_Driver_Library
    ../libraries/ArduinoJson
    ../libraries/ArduinoUniqueID
    ../libraries/AsyncTCP
    ../libraries/ESPAsyncWebServer-master
    ../libraries/ESPAsyncWiFiManager-master
    ../libraries/FastLED
    ../libraries/IoTT_CommDef
    ../libraries/IoTT_DigitraxBuffers
    ../libraries/IoTT_lbServer
    ../libraries/IoTT_LEDChain
    ../libraries/IoTT_LocoNetButtons
    ../libraries/IoTT_LocoNetESP32HB
    ../libraries/IoTT_MQTTESP32
    ../libraries/IoTT_RemoteButtons
    ../libraries/IoTT_SerInjector
    ../libraries/IoTT_Switches
    ../libraries/IoTT_TrainSensor
    ../libraries/M5Unified
    ../libraries/NmraDcc
    ../libraries/OneDimKalman
    ../libraries/PubSubClient
    ../libraries/TJpg_Decoder
    ../libraries/TMAG5273

build_flags =

extra_scripts = 
    post:pio-scripts/output_bins.py

; ------------------------------------------------------------
;   M5StickC  (auch gültig für M5StickC Plus)
;   das Image M5StickC Plus funktioniert für beide Sticks!
; ------------------------------------------------------------
[env:m5stickc]
board = m5stick-c
board_build.partitions = custom_2m_spiffs.csv
custom_dev_name = IoTTStickM5_Plus

platform_packages = 
    ${env.platform_packages}

build_flags =
    ${env.build_flags}
    ${common.custom_flags}
    -DRELEASE_NAME=\"IoTT-Stick-C\"
    -DARDUINO_M5Stick_C
    -DStickPlus

lib_deps =
    ${env.lib_deps}
    ${common.custom_libs}

lib_ignore = 
    ${env.lib_ignore}

extra_scripts = 
    pre:pio-scripts/update_config.py
    ${env.extra_scripts}
    post:pio-scripts/merge_m5stickc_plus.py
    post:pio-scripts/release_m5stickc_plus.py

; ------------------------------------------------------------
;   M5StickC Plus2
; ------------------------------------------------------------
[env:m5stickc_plus2]
board = m5stickc_plus2
custom_dev_name = IoTTStickM5_Plus2

platform_packages = 
    ${env.platform_packages}

build_flags =
    ${env.build_flags}
    ${common.custom_flags}
    -DStickPlus2
    -DRELEASE_NAME=\"IoTT-Stick-Plus2\"

lib_deps =
    ${env.lib_deps}
    ${common.custom_libs}

lib_ignore = 
    ${env.lib_ignore}

extra_scripts = 
    pre:pio-scripts/update_config.py
    ${env.extra_scripts}
    post:pio-scripts/merge_m5stickc_plus2.py
    post:pio-scripts/release_m5stickc_plus2.py
